name: garagum_racing
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1




environment:
  sdk: ^3.10.7




dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flame: ^1.35.1
  flame_forge2d: ^0.19.2+4
  flame_audio: ^2.11.5
  vector_math: ^2.1.4
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  flutter_lints: ^6.0.0



flutter:

  
  uses-material-design: true

  assets:
    - assets/images/vehicles/
    - assets/images/parallax/
    - assets/images/terrain/
    - assets/images/bridge/
    - assets/images/obstacles/
    - assets/images/ui/
    - assets/images/fx/
    - assets/images/images_ashgabat/buildings/
    - assets/images/images_ashgabat/deco/
    - assets/images/images_ashgabat/obstacles/
    - assets/images/images_ashgabat/parallax/
    - assets/images/images_ashgabat/terrain/
    - assets/images/images_ashgabat/vehicles/
    - assets/images/images_yangykala/cliffs/
    - assets/images/images_yangykala/obstacles/
    - assets/images/images_yangykala/parallax/
    - assets/images/images_yangykala/props/
    - assets/images/images_yangykala/terrain/
    - assets/images/images_yangykala/vehicles/
    - assets/images/images_derweze/crater/
    - assets/images/images_derweze/obstacles/
    - assets/images/images_derweze/parallax/
    - assets/images/images_derweze/props/
    - assets/images/images_derweze/terrain/
    - assets/images/images_derweze/vehicles/
    - assets/audio/
    - assets/audio/music/
    - assets/audio/sfx/

 

 
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
